import { Injectable } from '@angular/core';
import { Game } from '../models/game';
import { of, Observable } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class GameService {
  private mockGames: Game[] = [
    {
      id: 1,
      title: 'Hollow Knight: Silksong',
      price: 2499,
      image: 'assets/image/silksong.jpg',
      rating: 4.9,
      genre: { id: 2, name: 'Metroidvania', slug: 'metroidvania', description: 'Action-exploration platformer' },
      description: 'Играй за Хорнет — охотницу и принцессу, исследующую новое огромное королевство насекомых. Каждый уголок мира полон тайн, смертоносных врагов и эпических боссов.',
      developer: 'Team Cherry',
      releaseDate: 'TBA',
      screenshots: ['assets/image/silksong.jpg'],
    },
    {
      id: 2,
      title: 'Chivalry 2',
      price: 3499,
      originalPrice: 5999,
      discount: 42,
      image: 'assets/image/chivalry2.png',
      rating: 4.1,
      genre: { id: 3, name: 'Action', slug: 'action', description: 'Fast-paced multiplayer combat' },
      description: 'Эпические средневековые сражения на 64 игрока. Мечи, топоры, осадные орудия и крики боли — всё это Chivalry 2.',
      developer: 'Torn Banner Studios',
      releaseDate: '8 июня 2021',
      screenshots: ['assets/image/chivalry2.png'],
    },
    {
      id: 3,
      title: 'Mount & Blade II: Bannerlord',
      price: 4999,
      image: 'assets/image/bannerlord.png',
      rating: 4.3,
      genre: { id: 4, name: 'Strategy', slug: 'strategy', description: 'Medieval sandbox strategy RPG' },
      description: 'Строй армию, завоёвывай земли и стань правителем в огромном средневековом мире. Глубокая система политики, торговли и сражений.',
      developer: 'TaleWorlds Entertainment',
      releaseDate: '30 октября 2022',
      screenshots: ['assets/image/bannerlord.png'],
    },
    {
      id: 4,
      title: 'Battlefield 1',
      price: 2999,
      originalPrice: 4999,
      discount: 40,
      image: 'assets/image/battlefield1.jpg',
      rating: 4.4,
      genre: { id: 5, name: 'Shooter', slug: 'shooter', description: 'First-person military shooter' },
      description: 'Масштабные сражения Первой мировой войны — от окопов Европы до пустынь Аравии. Один из лучших шутеров серии по атмосфере.',
      developer: 'DICE',
      releaseDate: '21 октября 2016',
      screenshots: ['assets/image/battlefield1.jpg'],
    },
    {
      id: 5,
      title: 'Heroes of Might & Magic III: HD Edition',
      price: 1499,
      image: 'assets/image/homm3.jpg',
      rating: 4.8,
      genre: { id: 4, name: 'Strategy', slug: 'strategy', description: 'Turn-based fantasy strategy' },
      description: 'Легендарная пошаговая стратегия в HD. Собирай армии, захватывай замки, побеждай героев. Классика, не стареющая десятилетиями.',
      developer: 'New World Computing',
      releaseDate: '28 февраля 1999',
      screenshots: ['assets/image/homm3.jpg'],
    },
    {
      id: 6,
      title: 'Grand Theft Auto V',
      price: 3999,
      image: 'assets/image/gtav.jpg',
      rating: 4.7,
      genre: { id: 6, name: 'Open World', slug: 'open-world', description: 'Open world action-adventure' },
      description: 'Три преступника, один мегаполис. Ограбления, погони и хаос в Лос-Сантосе. Онлайн-режим с сотнями часов контента.',
      developer: 'Rockstar North',
      releaseDate: '17 сентября 2013',
      screenshots: ['assets/image/gtav.jpg'],
    },
    {
      id: 7,
      title: 'Frostpunk 2',
      price: 5499,
      image: 'assets/image/frostpunk2.jpg',
      rating: 4.5,
      genre: { id: 4, name: 'Strategy', slug: 'strategy', description: 'City-builder survival strategy' },
      description: 'Управляй последним городом человечества в постапокалиптическом ледяном мире. Каждое решение — моральная дилемма.',
      developer: '11 bit studios',
      releaseDate: '20 сентября 2024',
      screenshots: ['assets/image/frostpunk2.jpg'],
    },
    {
      id: 8,
      title: "Garry's Mod",
      price: 999,
      image: 'assets/image/garrysmod.png',
      rating: 4.6,
      genre: { id: 7, name: 'Sandbox', slug: 'sandbox', description: 'Physics sandbox game' },
      description: 'Физический конструктор без правил. Создавай, разрушай, играй во что хочешь. Тысячи мастерской-модов на любой вкус.',
      developer: 'Facepunch Studios',
      releaseDate: '29 ноября 2006',
      screenshots: ['assets/image/garrysmod.png'],
    },
    {
      id: 9,
      title: 'Squad',
      price: 4499,
      image: 'assets/image/squad.png',
      rating: 4.2,
      genre: { id: 5, name: 'Shooter', slug: 'shooter', description: 'Tactical military shooter' },
      description: 'Реалистичный тактический шутер с упором на командную работу и коммуникацию. Без слаженной команды не выжить.',
      developer: 'Offworld Industries',
      releaseDate: '23 сентября 2020',
      screenshots: ['assets/image/squad.png'],
    },
    {
      id: 10,
      title: 'Europa Universalis IV',
      price: 3999,
      image: 'assets/image/eu4.png',
      rating: 4.5,
      genre: { id: 4, name: 'Strategy', slug: 'strategy', description: 'Grand historical strategy' },
      description: 'Управляй государством от 1444 до 1821 года. Дипломатия, торговля, войны и колонии. Бесконечная реиграбельность.',
      developer: 'Paradox Development Studio',
      releaseDate: '13 августа 2013',
      screenshots: ['assets/image/eu4.png'],
    },
    {
      id: 11,
      title: 'The Elder Scrolls V: Skyrim Special Edition',
      price: 2999,
      originalPrice: 4999,
      discount: 40,
      image: 'assets/image/skyrim.png',
      rating: 4.6,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Open world fantasy RPG' },
      description: 'Легендарная RPG в мире викингов и драконов. Тысячи часов приключений, квестов и модов.',
      developer: 'Bethesda Game Studios',
      releaseDate: '28 октября 2016',
      screenshots: ['assets/image/skyrim.png'],
    },
    {
      id: 12,
      title: 'Hollow Knight',
      price: 1499,
      image: 'assets/image/hollowknight.png',
      rating: 4.9,
      genre: { id: 2, name: 'Metroidvania', slug: 'metroidvania', description: 'Action-exploration platformer' },
      description: 'Исследуй огромное подземное королевство насекомых. Мрачная атмосфера, сложные боссы и невероятный саундтрек.',
      developer: 'Team Cherry',
      releaseDate: '24 февраля 2017',
      screenshots: ['assets/image/hollowknight.png'],
    },
    {
      id: 13,
      title: 'Clair Obscur: Expedition 33',
      price: 6999,
      image: 'assets/image/expedition33.png',
      rating: 4.8,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Turn-based narrative RPG' },
      description: 'Пошаговая RPG с кинематографическим нарративом и уникальной боевой системой. Французская студия, мировой уровень.',
      developer: 'Sandfall Interactive',
      releaseDate: '24 апреля 2025',
      screenshots: ['assets/image/expedition33.png'],
    },
    {
      id: 14,
      title: 'Kingdom Come: Deliverance Royal Edition',
      price: 3999,
      originalPrice: 6999,
      discount: 43,
      image: 'assets/image/kcd.jpg',
      rating: 4.4,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Historical open world RPG' },
      description: 'Реалистичная RPG в средневековой Богемии 1403 года. Без магии — только история, выживание и честный бой.',
      developer: 'Warhorse Studios',
      releaseDate: '13 февраля 2018',
      screenshots: ['assets/image/kcd.jpg'],
    },
    {
      id: 15,
      title: 'The Witcher 3: Wild Hunt',
      price: 2499,
      originalPrice: 4999,
      discount: 50,
      image: 'assets/image/witcher3.png',
      rating: 5.0,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Open world action RPG' },
      description: 'Лучший ведьмак в лучшем из открытых миров. Гвинт, монстры и сложные выборы. Две масштабные DLC в комплекте.',
      developer: 'CD Projekt RED',
      releaseDate: '19 мая 2015',
      screenshots: ['assets/image/witcher3.png'],
    },
    {
      id: 16,
      title: 'Total War: Attila',
      price: 3499,
      image: 'assets/image/attila.png',
      rating: 4.3,
      genre: { id: 4, name: 'Strategy', slug: 'strategy', description: 'Historical turn-based strategy' },
      description: 'Останови Аттилу или стань им. Падение Западной Римской империи в твоих руках.',
      developer: 'Creative Assembly',
      releaseDate: '17 февраля 2015',
      screenshots: ['assets/image/attila.png'],
    },
    {
      id: 17,
      title: "Baldur's Gate 3",
      price: 7999,
      image: 'assets/image/bg3.png',
      rating: 5.0,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Turn-based D&D RPG' },
      description: 'Лучшая RPG десятилетия. D&D 5e в формате видеоигры — свобода выбора, глубокий нарратив и кооператив.',
      developer: 'Larian Studios',
      releaseDate: '3 августа 2023',
      screenshots: ['assets/image/bg3.png'],
    },
    {
      id: 18,
      title: 'Cyberpunk 2077',
      price: 2999,
      originalPrice: 5999,
      discount: 50,
      image: 'assets/image/cyberPunk2077.jpg',
      rating: 4.2,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Open world cyberpunk RPG' },
      description: 'Найт-Сити никогда не спит. Стань наёмником V и вступи в смертельную игру с корпорациями за выживание.',
      developer: 'CD Projekt RED',
      releaseDate: '10 декабря 2020',
      screenshots: ['assets/image/cyberPunk2077.jpg'],
    },
    {
      id: 19,
      title: 'Minecraft',
      price: 10000,
      image: 'assets/image/minecraft.jpg',
      rating: 5.0,
      genre: { id: 7, name: 'Sandbox', slug: 'sandbox', description: 'Sandbox survival indie game' },
      description: 'Строй, выживай, исследуй. Мир без ограничений и правил — только твоя фантазия определяет пределы.',
      developer: 'Mojang Studios',
      releaseDate: '18 ноября 2011',
      screenshots: ['assets/image/minecraft.jpg'],
    },
    {
      id: 20,
      title: 'The Witcher 4',
      price: 10000,
      image: 'assets/image/witcher.jpeg',
      rating: 4.0,
      genre: { id: 1, name: 'RPG', slug: 'rpg', description: 'Open world action RPG' },
      description: 'Новая глава в мире Ведьмака. Новый герой, новые монстры, знакомая глубина выбора и последствий.',
      developer: 'CD Projekt RED',
      releaseDate: 'TBA',
      screenshots: ['assets/image/witcher.jpeg'],
    },
  ];

  getGames(): Observable<Game[]> {
    return of(this.mockGames);
  }

  getGameById(id: number): Observable<Game | undefined> {
    return of(this.mockGames.find(g => g.id === id));
  }
}
